# .github/workflows/docker-publish.yml

name: Build and Push Docker Image

# This workflow runs whenever you push to the 'main' branch
on:
  push:
    branches: [ "main" ]

# Permissions needed for the workflow to write to GitHub Packages (Container Registry)
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    # Use the latest version of Ubuntu to run the job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Container Registry
      # This uses a special GITHUB_TOKEN for security
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build and push the Docker image
      # This action builds the image from your Dockerfile and pushes it to GHCR
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Tags the image with 'latest' and the commit SHA
          # Example: ghcr.io/your-username/your-repo-name:latest
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}